#include "cuda.h"
#include "cutil.h"

#define TEXFILT(x) tex_filt_##x

/*
filter texture
*/
texture<float,2> tex_filt_0;
texture<float,2> tex_filt_1;
texture<float,2> tex_filt_2;
texture<float,2> tex_filt_3;
texture<float,2> tex_filt_4;
texture<float,2> tex_filt_5;
texture<float,2> tex_filt_6;
texture<float,2> tex_filt_7;
texture<float,2> tex_filt_8;
texture<float,2> tex_filt_9;
texture<float,2> tex_filt_10;
texture<float,2> tex_filt_11;
texture<float,2> tex_filt_12;
texture<float,2> tex_filt_13;
texture<float,2> tex_filt_14;
texture<float,2> tex_filt_15;
texture<float,2> tex_filt_16;
texture<float,2> tex_filt_17;
texture<float,2> tex_filt_18;
texture<float,2> tex_filt_19;
texture<float,2> tex_filt_20;
texture<float,2> tex_filt_21;
texture<float,2> tex_filt_22;
texture<float,2> tex_filt_23;
texture<float,2> tex_filt_24;
texture<float,2> tex_filt_25;
texture<float,2> tex_filt_26;
texture<float,2> tex_filt_27;
texture<float,2> tex_filt_28;
texture<float,2> tex_filt_29;
texture<float,2> tex_filt_30;
texture<float,2> tex_filt_31;
texture<float,2> tex_filt_32;
texture<float,2> tex_filt_33;
texture<float,2> tex_filt_34;
texture<float,2> tex_filt_35;
texture<float,2> tex_filt_36;
texture<float,2> tex_filt_37;
texture<float,2> tex_filt_38;
texture<float,2> tex_filt_39;
texture<float,2> tex_filt_40;
texture<float,2> tex_filt_41;
texture<float,2> tex_filt_42;
texture<float,2> tex_filt_43;
texture<float,2> tex_filt_44;
texture<float,2> tex_filt_45;
texture<float,2> tex_filt_46;
texture<float,2> tex_filt_47;
texture<float,2> tex_filt_48;
texture<float,2> tex_filt_49;
texture<float,2> tex_filt_50;
texture<float,2> tex_filt_51;
texture<float,2> tex_filt_52;
texture<float,2> tex_filt_53;
texture<float,2> tex_filt_54;
texture<float,2> tex_filt_55;
texture<float,2> tex_filt_56;
texture<float,2> tex_filt_57;
texture<float,2> tex_filt_58;
texture<float,2> tex_filt_59;
texture<float,2> tex_filt_60;
texture<float,2> tex_filt_61;
texture<float,2> tex_filt_62;
texture<float,2> tex_filt_63;
